# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant write permissions for publishing to GitHub Packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # Corrected: Publish to GitHub Packages
          registry-url: https://npm.pkg.github.com/
          scope: '@damilary' # Replace with your GitHub username or organization name
      - run: npm ci
      - run: npm publish
        env:
          # For GitHub Packages, you typically use GITHUB_TOKEN for authentication
          # and it's automatically provided by GitHub Actions with appropriate permissions.
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
